In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
from matplotlib import pyplot as plt
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##Import

In [ ]:
%cd /content/drive/MyDrive/3401/Dataset/

/content/drive/MyDrive/3401/Dataset

In [ ]:
credits= pd.read_csv("credits.csv")
titles=pd.read_csv("titles.csv")

In [ ]:
combined = pd.merge(titles,credits,left_on="id",right_on="id")
combined = combined.drop('id', axis=1)
combined

,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,3748,Robert De Niro,Travis Bickle,ACTOR
1,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,14658,Jodie Foster,Iris Steensma,ACTOR
2,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,7064,Albert Brooks,Tom,ACTOR
3,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,3739,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,48933,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77796,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,736339,Adelaida Buscato,María Paz,ACTOR
77797,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,399499,Luz Stella Luengas,Karen Bayona,ACTOR
77798,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,373198,Inés Prieto,Fanny,ACTOR
77799,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,378132,Isabel Gaona,Cacica,ACTOR
77800,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,1950416,Julian Gaviria,NaN,DIRECTOR

In [ ]:
shows = combined[combined['type'] != 'MOVIE']
shows

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
163,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306,11472,Graham Chapman,Various,ACTOR
164,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306,11476,Michael Palin,"Various / ""It's"" man",ACTOR
165,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306,11475,Terry Jones,Various,ACTOR
166,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306,11474,Eric Idle,Various,ACTOR
167,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,73424.0,17.617,8.306,11473,Terry Gilliam,Various,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77655,ts288861,Let's Eat,SHOW,A food-blogging insurance agent encounters a f...,2021,TV-14,60,"['drama', 'comedy']",['TH'],1.0,tt15978704,8.2,5.0,2.334,NaN,142070,Maneerat Kam-Uan,Ae,ACTOR
77656,ts288861,Let's Eat,SHOW,A food-blogging insurance agent encounters a f...,2021,TV-14,60,"['drama', 'comedy']",['TH'],1.0,tt15978704,8.2,5.0,2.334,NaN,168201,Rudklao Amratisha,NaN,ACTOR
77657,ts288861,Let's Eat,SHOW,A food-blogging insurance agent encounters a f...,2021,TV-14,60,"['drama', 'comedy']",['TH'],1.0,tt15978704,8.2,5.0,2.334,NaN,171222,Jaturong Mokjok,NaN,ACTOR
77658,ts288861,Let's Eat,SHOW,A food-blogging insurance agent encounters a f...,2021,TV-14,60,"['drama', 'comedy']",['TH'],1.0,tt15978704,8.2,5.0,2.334,NaN,247588,Pisamai Wilaisak,NaN,ACTOR
77659,ts288861,Let's Eat,SHOW,A food-blogging insurance agent encounters a f...,2021,TV-14,60,"['drama', 'comedy']",['TH'],1.0,tt15978704,8.2,5.0,2.334,NaN,401236,Sarawut Wichiensarn,NaN,DIRECTOR

TODO: Average score by genre

TODO: Sort Actors by score

In [ ]:

grouped_df = shows.groupby('title').agg(set).reset_index()
grouped_df

,title,id,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,#blackAF,{ts236033},{SHOW},{A father takes an irreverent and honest appro...,{2020},{TV-MA},{37},{['comedy']},{['US']},{1.0},{nan},"{nan, nan, nan, nan, nan, nan, nan, nan}","{nan, nan, nan, nan, nan, nan, nan, nan}",{2.924},{7.1},"{1280777, 1060299, 1405871, 834162, 21715, 118...","{Ravi Cabot-Conyers, Rashida Jones, Richard Ga...","{Chloe Barris, Joya Barris, Brooklyn Barris, K...",{ACTOR}
1,100 Days My Prince,{ts83359},{SHOW},{Lee Yool falls off a cliff and nearly dies in...,{2018},{TV-14},{75},"{['drama', 'thriller', 'comedy', 'action', 'hi...",{['KR']},{1.0},{tt8199972},{7.7},{2068.0},{10.313},{8.323},"{75400, 137871, 948753, 858776, 110122, 296237...","{Kim Seon-ho, Jeong Joon-won, Ji Min-hyuk, Lee...","{nan, Kim So-hye, Kim Soo-Ji, Hong-sim / Yoon ...","{DIRECTOR, ACTOR}"
2,100 Humans: Life's Questions. Answered.,{ts226588},{SHOW},{One hundred hardy souls from diverse backgrou...,{2020},{TV-14},{37},"{['documentation', 'reality']}",{['US']},{1.0},{tt11823088},{5.7},{4055.0},{3.447},{6.4},"{1922852, 1363723, 1923218, 1120189, 1651806}","{Braxton Hale, Alfredo Tavares, Haley Bockrath...","{Human #90, Human #64, Human #72, Human #84, H...",{ACTOR}
3,13 Reasons Why,{ts42294},{SHOW},"{After a teenage girl's perplexing suicide, a ...",{2017},{TV-MA},{58},"{['drama', 'thriller']}",{['US']},{4.0},{tt1837492},{7.5},{286015.0},{80.574},{7.748},"{282177, 1025665, 112323, 23717, 15238, 119053...","{Deaken Bluman, Ross Butler, Gary Sinise, Amy ...","{Clay Jensen, Tony Padilla, Winston Williams, ...",{ACTOR}
4,13 Reasons Why: Beyond the Reasons,{ts82424},{SHOW},"{Cast members, writers, producers and mental h...",{2017},{TV-MA},{42},{['documentation']},{['US']},{3.0},{tt8615966},{6.2},{328.0},{11.431},{6.5},"{282176, 16431, 1573071, 5144, 1119}","{Jay Asher, Selena Gomez, Katherine Langford, ...",{Self},{ACTOR}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1826,revisions,{ts84639},{SHOW},{An isolated city. An unknown enemy. An uncert...,{2019},{TV-MA},{23},"{['animation', 'action', 'scifi']}",{['JP']},{1.0},{tt9522354},{5.9},{612.0},{4.35},{7.0},"{12003, 115686, 3590, 97290, 138, 204, 274, 10...","{Nobunaga Shimazaki, Manaka Iwami, Yoko Hikasa...","{Milo, Chang Lu Steiner, Keisaku Asano, Temari...",{ACTOR}
1827,นางสาวก้นครัว,{ts223454},{SHOW},"{""Miss Culinary"" reveals the brilliance of a y...",{2019},{TV-14},{0},{[]},{['TH']},{1.0},{nan},"{nan, nan, nan, nan, nan}","{nan, nan, nan, nan, nan}",{2.431},{8.0},"{1850528, 271137, 141199, 163259, 707327}","{Thanabordee Jaiyen, Jason Young, Chonnikan Ne...",{nan},{ACTOR}
1828,ปริศนาล่าข้ามเวลา,{ts223062},{SHOW},{nan},{2019},{TV-14},{60},{[]},{['TH']},{1.0},{nan},{nan},{nan},{1.473},{7.0},{646657},{Morakot Liu},{nan},{ACTOR}
1829,糖糖Online,{ts222901},{SHOW},"{When a wardrobe malfunction goes viral, a bub...",{2019},{TV-MA},{24},"{['drama', 'family']}",{['TW']},{1.0},{tt11330500},{5.4},{22.0},{0.6},{10.0},"{1260133, 1260135, 1186315, 1260082, 1260020, ...","{Chiao Yuan-Yuan, Cheng Ko, Suun Lin, Dean Tan...","{Jian Da-Cheng, Lin Jia-Qi, Zhang Su-Qin, Zhan...",{ACTOR}
1830,냉면 랩소디,{ts307816},{SHOW},"{Refreshing and flavorful, naengmyeon is Korea...",{2021},{TV-PG},{49},{['documentation']},{['KR']},{1.0},{tt15772846},{7.5},{25.0},{1.765},{4.0},{310549},{Baek Jong-won},{nan},{ACTOR}